### ISSUE TITLE
implement

### ISSUE THREAD

**Issue by urrusjm** [energia/c2000-core#1]
Hi, i want to know how to implement this core in the energia ide 1.6.10E18. I'm already trying to make c2000 works but i can't make it.
I follow the steps in the energia guide for the c2000 but the board does not appear in the board menu. 
When i use an old ide like 0101E0017 the board appear in the menu but qhen i want to upload a sketch the ide give me an error "don't found avr-g++". I google it all but i'm stuck.

Thanks in advance.

**Comment by robertinant** [comment]
@urrusjm, this core is still under development and will be released through the board manager in a couple weeks.
